version: '3.8'

x-common:
  database:
    &db-environment
      MYSQL_PASSWORD: &db-password "secure_mysql_password"
      MYSQL_ROOT_PASSWORD: "secure_mysql_root_password"
  panel:
    &panel-environment
      APP_URL: "http://example.com"
      APP_TIMEZONE: "UTC"
      APP_SERVICE_AUTHOR: "noreply@example.com"
      # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
      # to generate an SSL certificate for the Panel.
      # LE_EMAIL: ""
  mail:
    &mail-environment
      MAIL_FROM: "noreply@example.com"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "mail"
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/zeruheatvip/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "zeruheatvip"
      
  cache:
    image: redis:alpine
    restart: always

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "/srv/zeruheatvip/var/:/app/var/"
      - "/srv/zeruheatvip/nginx/:/etc/nginx/http.d/"
      - "/srv/zeruheatvip/certs/:/etc/letsencrypt/"
      - "/srv/zeruheatvip/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    command: >
      bash -c '
        # Your registration logic here
        echo "Registration logic executed.";
        # Redirect to Telegram registration link
        TELEGRAM_URL="https://t.me/<LuciferVXII_Indonesia>?start=zeruheatvip_registration"
        echo "Click the link to register: $TELEGRAM_URL"
      '
      
